### ISSUE TITLE
MemoryError default_w.txt 98Gi

### ISSUE THREAD

**Issue by BerKer999** [akhatkulov/InstaCracker-CLI#4]
│ /root/InstaCracker-CLI/helper/default.py:23 in __init__                                          │
│                                                                                                  │
│   20 │   │   │   print(' The tool was arrested exit ')                                           │
│   21 │   │   │   sys.exit()                                                                      │
│   22 │   │   with open("default_w.txt", 'r+') as x:                                              │
│ ❱ 23 │   │   │   Combolist = x.read().splitlines()                                               │
│   24 │   │   thread = []                                                                         │
│   25 │   │   self.Coutprox = 0                                                                   │
│   26 │   │   for combo in Combolist:                                                             │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮               │
│ │    Combo = 'default_w.txt'                                                     │               │
│ │        i = 9                                                                   │               │
│ │     self = <helper.default.default_start object at 0x78976fb67eb0>             │               │
│ │       sp = <click._termui_impl.ProgressBar object at 0x78976fb65870>           │               │
│ │ username = 'victoriaa_bl03'                                                    │               │
│ │        x = <_io.TextIOWrapper name='default_w.txt' mode='r+' encoding='UTF-8'>

**Comment by akhatkulov** [comment]
?

**Comment by Athwal12345** [comment]
Problem

**Comment by akhatkulov** [comment]
oh men sorry, all bugs are fixed!
